spring:
  jpa:
    properties:
      hibernate:
        cache:
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  flyway:
    locations: classpath:db/migration/
    baseline-on-migrate: true
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    schemas: events
    enabled: true
    placeholder-replacement: false
    table: schema_version
  mail:
    host: smtp.gmail.com
    port: 587
    username: boiechko.work@gmail.com
    password: 28171821
    test-connection: true

server:
  port: 8082

google:
  scope: profile email https://www.googleapis.com/auth/user.gender.read https://www.googleapis.com/auth/user.birthday.read https://www.googleapis.com/auth/user.addresses.read https://www.googleapis.com/auth/user.phonenumbers.read https://www.googleapis.com/auth/user.emails.read
  auth-url: https://accounts.google.com/o/oauth2/v2/auth
  api-url: https://people.googleapis.com/v1
  refresh-token-expires-in-days: 180

facebook:
  scope: public_profile,email,read_insights,user_birthday,user_location
  api-url: https://graph.facebook.com/v15.0
  redirect-url: ${base-url}/api/facebook

jwt:
  secret: tU3c8tELeCQ2avgNG8AU
  validation-time-in-sec: 604800

rest-template:
  read-timeout-in-minutes: 2
  connect-timeout-in-minutes: 2