spring:
  datasource:
    jdbc-url: jdbc:mysql://${datasource.domain}:${datasource.port}/${datasource.schema}?user=${datasource.user}&password=${datasource.password}&serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false


google:
  clientId: 234278654569-kv92p5pf7mdvtbcnt76boh2rjvnqhrub.apps.googleusercontent.com
  clientSecret: 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
  redirect-url: ${base-url}/api/google

facebook:
  appId: 755177369114699
  appSecret: 90ab026ae80a8cf5cd75bb067f870e65

base-url: http://localhost:8082

datasource:
  schema: events
  port: 3306
  user: root
  password: XNmX4kRyhAlSVJAmOrAY
  domain: eventsdb.cyc1auelzdk5.eu-central-1.rds.amazonaws.com