spring:
  jpa:
    properties:
      hibernate:
        cache:
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  flyway:
    locations: classpath:db/migration/
    baseline-on-migrate: true
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    schemas: events
    enabled: true
    placeholder-replacement: false
    table: schema_version
  mail:
    host: smtp.gmail.com
    port: 587
    username: boiechko.work@gmail.com
    password: 28171821
    test-connection: true

server:
  port: 8082

jwt:
  secret: tU3c8tELeCQ2avgNG8AU
  validation-time-in-sec: 604800

rest-template:
  read-timeout-in-minutes: 2
  connect-timeout-in-minutes: 2