spring:
  datasource:
    jdbc-url: jdbc:mysql://${datasource.domain}:${datasource.port}/${datasource.schema}?user=${datasource.user}&password=${datasource.password}&serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        cache:
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  flyway:
    locations: classpath:db/migration/
    baseline-on-migrate: true
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    schemas: events
    enabled: true
    placeholder-replacement: false
    table: schema_version
  mail:
    host: smtp.gmail.com
    port: 587
    username: boiechko.work@gmail.com
    password: 28171821
    test-connection: true

google:
  clientId: 234278654569-kv92p5pf7mdvtbcnt76boh2rjvnqhrub.apps.googleusercontent.com
  clientSecret: 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
  scope: profile email https://www.googleapis.com/auth/user.gender.read https://www.googleapis.com/auth/user.birthday.read https://www.googleapis.com/auth/user.addresses.read https://www.googleapis.com/auth/user.phonenumbers.read https://www.googleapis.com/auth/user.emails.read
  auth-url: https://accounts.google.com/o/oauth2/v2/auth
  api-url: https://people.googleapis.com/v1
  redirect-url: ${base-url}/api/google
  refresh-token-expires-in-days: 180

base-url: http://localhost:8082

datasource:
  schema: events
  port: 3306
  user: events
  password: CYqawSWfHjLfNzYT1@
  domain: localhost

server:
  port: 8082

jwt:
  secret: tU3c8tELeCQ2avgNG8AU
  validation-time-in-sec: 604800

rest-template:
  read-timeout-in-minutes: 2
  connect-timeout-in-minutes: 2