name: Run maven tests on push or pull request to master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-compile:
    needs: run-compile
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'read'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
      - id: 'compile'
        name: 'Set up JDK 11'
        uses: 'actions/setup-java@v3'
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: 'Run maven tests'
        run: mvn clean test