name: Run maven tests

on:
  workflow_run:
    workflows:
      [ "Run maven compile" ]
    types:
      - completed

jobs:
  run-test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'read'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - id: 'compile'
        name: 'Set up JDK 11'
        uses: 'actions/setup-java@v3'
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: 'Run maven tests'
        run: mvn clean test